### ISSUE TITLE
Add Summoning

### ISSUE THREAD

**Issue by gmiclotte** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#32]
- [x] interface for equipping summons
- [x] interface for activating synergies
- [x] import equipped summons, see #38
- [x] add required summoning level to the level display
- [x] add charge use -> 1 (of each) per summon attack, 2 of each if synergy active, see also #33
- [x] implement summon effects, damage is done, modifiers should be covered by #33, is there anything else?
- [x] implement synergies
- [x] Add synergies modifiers to the modifiers object

**Comment by gmiclotte** [comment]
- [ ] 0 1 Golbin Thief Occultist Upon killing an Enemy, grants GP equal to 10% of their highest base Evasion Rating. {summoningSynergy_0_1: 10}
- [ ] 0 2 Golbin Thief Wolf Upon killing an Enemy, grants +200 GP. {increasedGPFromMonstersFlat: 200}
- [ ] 0 6 Golbin Thief Minotaur Grants GP equal to 25% of your MELEE damage dealt. {summoningSynergy_0_6: 25}
- [ ] 0 7 Golbin Thief Centaur Grants GP equal to 20% of your RANGED damage dealt. {summoningSynergy_0_7: 20}
- [ ] 0 8 Golbin Thief Witch Grants GP equal to 15% of your MAGIC damage dealt. {summoningSynergy_0_8: 15}
- [ ] 0 12 Golbin Thief Cyclops Upon killing a Slayer Task Enemy, grants +50% GP. {summoningSynergy_0_12: 50}
- [ ] 0 13 Golbin Thief Yak Upon being hit by an Enemy, grants GP equal to (20 * Your Damage Reduction). This can only proc once every Enemy Attack Turn. {summoningSynergy_0_13: 20}
- [ ] 0 14 Golbin Thief Unicorn Every time you regenerate Hitpoints (Not eating), grants GP equal to (100 * Hitpoints Regenerated). {summoningSynergy_0_14: 1}
- [ ] 0 15 Golbin Thief Dragon Upon killing an Enemy that is BURNING, grants +100% GP. {summoningSynergy_0_15: 100}
- [ ] 1 2 Occultist Wolf When player has full HP, effects from the Occultist Familiar are tripled. {summoningSynergy_1_2: 1}
- [ ] 1 6 Occultist Minotaur -15% Enemy Melee Evasion Rating. {decreasedEnemyMeleeEvasion: 15}
- [ ] 1 7 Occultist Centaur -15% Enemy Ranged Evasion Rating. {decreasedEnemyRangedEvasion: 15}
- [ ] 1 8 Occultist Witch +100 Magic Defence Bonus. {summoningSynergy_1_8: 100}
- [ ] 1 12 Occultist Cyclops If the Enemy is your current Slayer Task, -15% Enemy Accuracy Rating. {summoningSynergy_1_12: 15}
- [ ] 1 13 Occultist Yak Grants flat Melee & Ranged Defence Bonus equal to your Damage Reduction {summoningSynergy_1_13: 1}
- [ ] 1 14 Occultist Unicorn If the Enemy has more combined Evasion Ratings than the Player, grants +1% Hitpoint Regeneration. {summoningSynergy_1_14: 1}
- [ ] 1 15 Occultist Dragon If the Player is BURNING, grants +75 Melee, Ranged and Magic Defence Bonus. {summoningSynergy_1_15: 75}
- [ ] 2 6 Wolf Minotaur If using a Melee Attack Style, grants +6% Lifesteal. {summoningSynergy_2_6: 6}
- [ ] 2 7 Wolf Centaur If using a Ranged Attack Style, grants +4% Lifesteal. {summoningSynergy_2_7: 4}
- [ ] 2 8 Wolf Witch If using a Magic Attack Style, grants +2% Lifesteal. {summoningSynergy_2_8: 2}
- [ ] 2 12 Wolf Cyclops Grants Slayer Coins equal to 5% of HP leeched from Lifesteal. {summoningSynergy_2_12: 5}
- [ ] 2 13 Wolf Yak Upon attacking an Enemy, heals you for 50% of your Damage Reduction. This can only proc once every 2 seconds. {summoningSynergy_2_13: 50}
- [ ] 2 14 Wolf Unicorn +1% Lifesteal from Bleed damage. {summoningSynergy_2_14: 1}
- [ ] 2 15 Wolf Dragon Heals you for all damage dealt by the Wolf & Dragon Familiars. {summoningSynergy_2_15: 1}
- [ ] 6 7 Minotaur Centaur While fighting a Ranged Enemy, grants +15 Melee Accuracy Bonus and +15 Melee Strength Bonus. {summoningSynergy_6_7: 15}
- [ ] 6 8 Minotaur Witch While fighting your current Slayer Task, grants +5% of your Magic Max Hit as Minimum Damage. {summoningSynergy_6_8: 5}
- [ ] 6 12 Minotaur Cyclops While fighting your current Slayer Task, grants +10% of your Melee Max Hit as Minimum Damage. {summoningSynergy_6_12: 10}
- [ ] 6 13 Minotaur Yak While fighting a Ranged Enemy, grants +2% Damage Reduction. {summoningSynergy_6_13: 2}
- [ ] 6 14 Minotaur Unicorn While using a Melee Weapon, grants +8% of your Melee Max Hit as Flat HP Regen. {summoningSynergy_6_14: 8}
- [ ] 6 15 Minotaur Dragon If the Enemy is BURNING, effects from the Minotaur Familiar are tripled. {summoningSynergy_6_15: 1}
- [ ] 7 8 Centaur Witch While fighting a Magic Enemy, grants +15 Ranged Accuracy Bonus and +15 Ranged Strength Bonus. {summoningSynergy_7_8: 15}
- [ ] 7 12 Centaur Cyclops While fighting your current Slayer Task, grants +10% of your Ranged Max Hit as Minimum Damage. {summoningSynergy_7_12: 10}
- [ ] 7 13 Centaur Yak While fighting a Magic Enemy, grants +2% Damage Reduction. {summoningSynergy_7_13: 2}
- [ ] 7 14 Centaur Unicorn While using a Ranged Weapon, grants +7% of your Ranged Max Hit as HP Regeneration. {summoningSynergy_7_14: 7}
- [ ] 7 15 Centaur Dragon Your Ranged Attacks now have +20% to inflict BURNING on the Enemy. {summoningSynergy_7_15: 20}
- [ ] 8 12 Witch Cyclops Grants Slayer Coins equal to 2% of your Magic Damage. {summoningSynergy_8_12: 2}
- [ ] 8 13 Witch Yak While fighting a Melee Enemy, grants +2% Damage Reduction. {summoningSynergy_8_13: 2}
- [ ] 8 14 Witch Unicorn Grants +5% of your Max Hit as HP Regeneration if using a Magic Attack Style. {summoningSynergy_8_14: 5}
- [ ] 8 15 Witch Dragon +30 Minimum Damage for all Standard Magic Spells. {increasedMinAirSpellDmg: 3, increasedMinWaterSpellDmg: 3, increasedMinEarthSpellDmg: 3, increasedMinFireSpellDmg: 3}
- [ ] 12 13 Cyclops Yak While fighting your current Slayer Task, +3% Damage Reduction. {summoningSynergy_12_13: 3}
- [ ] 12 14 Cyclops Unicorn While fighting your current Slayer Task, +150% Hitpoints Regeneration. {summoningSynergy_12_14: 150}
- [ ] 12 15 Cyclops Dragon You take 25% less damage from Dragonbreath Special Attacks. {summoningSynergy_12_15: 25}
- [ ] 13 14 Yak Unicorn +200% Hitpoints Regeneration if you have less than 75% Current HP. {summoningSynergy_13_14: 200}
- [ ] 13 15 Yak Dragon You take no damage from BURNING. {summoningSynergy_13_15: 1}
- [ ] 14 15 Unicorn Dragon You now heal for all BURNING damage you or the Dragon Familiar applies. {summoningSynergy_14_15: 1}

**Comment by gmiclotte** [comment]
Double check `calculateMiscSummoningModifiers`

**Comment by gmiclotte** [comment]
Broken in v1.4.0-2 (list might be incomplete !)
- [ ] 6 8 Minotaur Witch While fighting your current Slayer Task, grants +5% of your Magic Max Hit as Minimum Damage. {summoningSynergy_6_8: 5}
- [ ] 6 14 Minotaur Unicorn While using a Melee Weapon, grants +8% of your Melee Max Hit as Flat HP Regen. {summoningSynergy_6_14: 8}
- [ ] 8 14 Witch Unicorn Grants +5% of your Max Hit as HP Regeneration if using a Magic Attack Style. {summoningSynergy_8_14: 5}
